name: Build & publish ICS
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build && node dist/cli.js --provider tides
        env:
          STORM_TOKEN: ${{ secrets.STORM_TOKEN }}

      - name: Commit calendar
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tides.ics
          git commit -m "chore: update calendar" || echo "no changes"
          git push
